workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Upgrade Flutter SDK
        script: |
          flutter upgrade
      - name: Run Flutter tests
        script: |
          flutter test
